### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by ahsan98** [ahmadx16/IceAndFire_Django#1]
Read more about requirements.txt: https://medium.com/@boscacci/why-and-how-to-make-a-requirements-txt-f329c685181e#:~:text=In%20short%2C%20we%20generate%20and,Python%20code%20we've%20written.

PS: The pip freeze approach is not recommended. Add the packages you install manually to requirements.txt with versions (use pip freeze for versions) donot add all packages only those you directly installed (don't add dependencies)

**Comment by ahmadx16** [comment]
Yep! a solid approach 👍.
